#!/usr/bin/env python3
# SPDX-License-Identifier: LicenseRef-Sustainable-Use
"""Build the Megaton mod for Fallout 2.

    python3 mod/megaton/build.py [--out DIR] [--stage FILE.py] [--only a,b] [step ...]   (default: all native build steps)

Steps
    ids      write scripts/ids.h (script numbers, GVARs, item PIDs, map/area ids) and
             scripts/tiles.h (named map spots) from registry.py and layout/spots.py
    data     stage the edited game tables (maps.txt, city.txt, scripts.lst, *.msg, quests)
             and the world map's MEGATON plate (art/intrface, worldmap_art.py)
    protos   create the mod's new item protos (protos.py)
    art      stage the custom pre-rendered art of mod/megaton-art (sprites, scenery and wall
             protos; its list and message additions are merged into the staged copies)
    scripts  compile with the pinned compiler, or copy verified production prebuilts;
             stage the current dialogue .msg files
    maps     generate the .map files (layout/, or the module given with --stage)
    lint     check the staged tables the way the engine parses them
    pack     write out/patch001.dat (the form the game loads)
    web      unavailable: browser hosting is not distributed in this repository

The art step copies the prepared mod/megaton-art/out tree, numbered by manifest.json.
Player setup restores committed own sprites and composes game-derived tiles locally.
Blender rendering is a separate author operation; see docs/testing.md. The generated
patch001.dat contains the native mod and stays outside the source repository.

Everything is staged under mod/megaton/out/ (or --out DIR, so several people
can build test variants side by side) using the game's own lower-case paths.
--only limits the scripts step to the listed script stems (someone else's
half-written script then cannot break your build). The mod ships as
patch001.dat because the engine searches patchNNN.dat archives before the
loose data/ folder, and patch000.dat already contains maps.txt, city.txt,
scripts.lst and friends: loose copies would be ignored.

--stage FILE.py replaces the real town with a small test map (stagekit.py
builds one in a single call). The stage file must define build_maps(out_dir),
which writes maps/megaton.map there, and may define two more names:

    SPOTS = {name: (hx, hy, rotation)}   spots the stage moved (stagekit.compact());
                                         every script is then compiled with matching
                                         TILE_<name> / ROT_<name> values instead of tiles.h's
    SCRIPTS_DIR = "scripts"              directory (relative to the stage file) searched
                                         for <stem>.ssl / <stem>.msg BEFORE scripts/: stand-ins
                                         for scripts that are not written yet, or test rigs

Easiest way to build and run a test: python3 mod/megaton/test.py -h
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "out")
SCRIPTS_SRC = os.path.join(HERE, "scripts")

sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
import registry  # noqa: E402

CITY_COUNT = 49  # worldmap.h: the engine exits unless city.txt has exactly this many areas
AUTOMAP_MAP_COUNT = 160  # automap.h: size of the per-map automap tables


# ---------------------------------------------------------------- text helpers

def read_vanilla(rel):
    from f2lib import GameFiles
    return GameFiles().read(rel).decode("latin-1")


def write_out(rel, text):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text.encode("latin-1"))
    return path


def write_atomic(path, text):
    """Generated headers are shared by concurrent builds: never expose a half-written file."""
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)


def append_lines(text, lines):
    """Append CRLF lines; the vanilla tables do not end with a newline."""
    if not text.endswith("\n"):
        text += "\r\n"
    return text + "\r\n".join(lines) + "\r\n"


def vanilla_script_count():
    text = read_vanilla("scripts/scripts.lst")
    return len(text.replace("\r\n", "\n").rstrip("\n").split("\n"))


def script_ids():
    """{stem: (0-based scripts.lst index, 1-based script number)} for our scripts."""
    base = vanilla_script_count()
    return {stem: (base + i, base + i + 1) for i, (stem, _, _) in enumerate(registry.SCRIPTS)}


# ---------------------------------------------------------------- steps

def step_ids():
    ids = script_ids()
    lines = [
        "// Generated by build.py from registry.py - do not edit.",
        "#ifndef MEGATON_IDS_H",
        "#define MEGATON_IDS_H",
        "",
        "// Script numbers (1-based, as used by create_object_sid, message_str,",
        "// gsay_*/giq_option and map headers).",
    ]
    for stem, (_, number) in ids.items():
        lines.append(f"#define SCRIPT_{stem.upper():<12} ({number})")
    lines += ["", "// Global variables (reserved vanilla slots)."]
    for name, value in registry.GVARS.items():
        lines.append(f"#define {name:<28} ({value})")
    lines += ["", "// Vanilla global variables the mod reads or writes."]
    for name, value in registry.VANILLA_GVARS.items():
        lines.append(f"#define {name:<28} ({value})")
    lines += ["", "// Bits of GVAR_MG_FLAGS."]
    for name, value in registry.FLAGS.items():
        lines.append(f"#define {name:<28} ({value})")
    lines += ["", "// Maps and world map."]
    for index, _, stem, _, _ in registry.MAPS:
        lines.append(f"#define MAP_{stem.upper():<15} ({index})")
    lines += ["", "// New items."]
    for name, pid, _, _, _ in registry.ITEMS:
        lines.append(f"#define {name:<28} ({pid})")
    art = sync_art_ledger()
    if art:
        lines += ["", "// Custom art (mod/megaton-art; slots recorded in art_ids.json)."]
        for name, pid in art.items():
            lines.append(f"#define {name:<28} (0x{pid:08X})")
        for name, frame in registry.ART_BOMB_FRAMES.items():
            lines.append(f"#define {name:<28} ({frame})")
    lines += [
        "",
        f"#define AREA_MEGATON        ({registry.AREA})",
        f"#define MEGATON_WORLD_X     ({registry.WORLD_MAP_EXIT_POS[0]})",
        f"#define MEGATON_WORLD_Y     ({registry.WORLD_MAP_EXIT_POS[1]})",
        "",
        "#endif",
        "",
    ]
    os.makedirs(SCRIPTS_SRC, exist_ok=True)
    path = os.path.join(SCRIPTS_SRC, "ids.h")
    write_atomic(path, "\n".join(lines))
    from layout import spots

    tiles = ["// Generated by build.py from layout/spots.py - do not edit.",
             "// Each name can be predefined (a test stage that moves spots compiles its scripts",
             "// with -D TILE_<NAME>=..., see build.py --stage), hence the #ifndef around every line.",
             "#ifndef MEGATON_TILES_H", "#define MEGATON_TILES_H", ""]
    for name, (hx, hy, rotation) in spots.SPOTS.items():
        tiles += [f"#ifndef TILE_{name}", f"#define TILE_{name:<20} ({hy * 200 + hx})", "#endif",
                  f"#ifndef ROT_{name}", f"#define ROT_{name:<21} ({rotation})", "#endif"]
    tiles += ["", "#endif", ""]
    write_atomic(os.path.join(SCRIPTS_SRC, "tiles.h"), "\n".join(tiles))
    print(f"ids: {os.path.relpath(path, ROOT)} ({len(ids)} scripts, {len(registry.GVARS)} gvars, {len(registry.ITEMS)} items, {len(spots.SPOTS)} spots)")


# ---------------------------------------------------------------- custom art
ART_KINDS = {
    # kind: (art / proto directory, message file of the protos' names)
    "scenery": ("scenery", "text/english/game/pro_scen.msg"),
    "wall": ("walls", "text/english/game/pro_wall.msg"),
}
ART_PAD = "mgpad.pro"
ART_PAD_FRM = "mgpad.frm"
ART_TILE_LIMIT = 4096


def art_out():
    return os.path.join(registry.art_dir(), "out")


def art_files(manifest):
    """Game paths of every sprite and proto the manifest numbers (lists and messages apart)."""
    files = []
    for kind, (folder, _) in ART_KINDS.items():
        prefix = registry.ART_PREFIX[kind]
        slots = manifest["slots"][kind]
        for index, slot in enumerate(slots):
            if slot.get("reserved"):
                continue  # reserved numbers share padding list entries, with no numbered file
            files.append(f"art/{folder}/{prefix}{index:04d}.frm")
            files.append(f"proto/{folder}/{prefix}{index:04d}.pro")
        files.append(f"proto/{folder}/{ART_PAD}")
        if any(slot.get("reserved") for slot in slots):
            files.append(f"art/{folder}/{ART_PAD_FRM}")
    for index in range(len(manifest.get("tiles", {}).get("slots", []))):
        files.append(f"art/tiles/mgt{index:04d}.frm")
    return files


def sync_art_ledger():
    """Check the art manifest against the append-only ledger and record new slots.

    Returns {define: PID} of registry.ART_NAMES ({} when mod/megaton-art has no manifest)."""
    manifest = registry.art_manifest()
    if manifest is None:
        print("ids: mod/megaton-art/manifest.json is missing: no custom art")
        return {}
    path = os.path.join(HERE, registry.ART_LEDGER)
    saved = {}
    if os.path.exists(path):
        with open(path) as f:
            saved = json.load(f)
    ledger = dict(saved.get("slots", {"scenery": [], "wall": []}))
    for field, expected in (("first_pid", registry.ART_FIRST_PID), ("first_art", registry.ART_FIRST_ART)):
        if field in saved and saved[field] != expected:
            raise SystemExit(f"ids: art_ids.json {field} differs from the registry: shipped bases cannot move")
    changed = False
    for kind in ART_KINDS:
        if manifest["ids"][kind]["pid_index"] != registry.ART_FIRST_PID[kind]:
            raise SystemExit(f"ids: the art manifest starts {kind} PIDs at {manifest['ids'][kind]['pid_index']}, "
                             f"registry.ART_FIRST_PID says {registry.ART_FIRST_PID[kind]}")
        keys = [slot["key"] for slot in manifest["slots"][kind]]
        recorded = ledger.get(kind, [])
        for index, key in enumerate(recorded):
            if index >= len(keys) or keys[index] != key:
                now = keys[index] if index < len(keys) else "nothing"
                raise SystemExit(f"ids: art {kind} slot {index} (PID {registry.ART_FIRST_PID[kind] + index}) was shipped as "
                                 f"{key!r} and is now {now!r}: maps and saves hold that number (art_ids.json is append-only)")
        if len(keys) > len(recorded):
            ledger[kind] = keys
            changed = True
    tile_ledger = saved.get("tiles")
    tile_manifest = manifest.get("tiles")
    if tile_manifest is None:
        if tile_ledger is not None:
            raise SystemExit("ids: the art manifest lost its shipped tile ledger")
    else:
        first = tile_manifest["first_index"]
        stock_count = len(_lines(read_vanilla("art/tiles/tiles.lst").encode("latin-1")))
        keys = [slot["key"] for slot in tile_manifest["slots"]]
        if first != stock_count or first + len(keys) > ART_TILE_LIMIT:
            raise SystemExit("ids: custom tiles must follow the stock list and fit the engine's 4096 slots")
        if len(set(keys)) != len(keys):
            raise SystemExit("ids: duplicate custom tile slot keys")
        if tile_ledger is not None:
            if tile_ledger["first_index"] != first:
                raise SystemExit("ids: shipped custom tile first_index cannot move")
            for index, key in enumerate(tile_ledger["slots"]):
                if index >= len(keys) or keys[index] != key:
                    raise SystemExit(f"ids: custom tile {first + index} changed or disappeared: art_ids.json is append-only")
        current = {"first_index": first, "slots": keys}
        changed |= current != tile_ledger
        tile_ledger = current
    if set(registry.ART_BOMB_FRAMES.values()) != set(range(int(manifest["pieces"]["mgb_bomb_states"]["frames"]))):
        raise SystemExit("ids: registry.ART_BOMB_FRAMES does not match the frames of mgb_bomb_states")
    if changed:
        document = {"about": "Append-only record of every custom-art slot the Megaton mod has shipped (see registry.py, "
                             "custom art). Written by build.py ids from mod/megaton-art/manifest.json; never edit or reorder.",
                    "first_pid": registry.ART_FIRST_PID, "first_art": registry.ART_FIRST_ART, "slots": ledger}
        if tile_ledger is not None:
            document["tiles"] = tile_ledger
        write_atomic(path, json.dumps(document, indent=1) + "\n")
    return registry.art_pids(manifest)


def _lines(data):
    return data.decode("latin-1").replace("\r\n", "\n").rstrip("\n").split("\n")


def merge_art_list(rel, stock_count_is_fixed):
    """Lay the art mod's lines of a .lst over the staged (or stock) copy of the same file.

    The art's file is the stock list plus its own lines (proto lists: plus padding lines up to
    its first PID). A line the town changed below that stays the town's; a padding line the
    town has used stays the town's; two different new lines on one number are a collision."""
    with open(os.path.join(art_out(), rel), "rb") as f:
        art = _lines(f.read())
    stock = _lines(read_vanilla(rel).encode("latin-1"))
    if art[:len(stock)] != stock:
        raise SystemExit(f"art: mod/megaton-art/out/{rel} does not begin with the stock list: rebuild the art (build.py data)")
    staged = os.path.join(OUT, rel)
    merged = list(art)
    if os.path.exists(staged):
        with open(staged, "rb") as f:
            town = _lines(f.read())
        for index, line in enumerate(town):
            if index >= len(merged):
                merged.append(line)
            elif line != merged[index]:
                ours = merged[index].split(";")[0].strip().lower()
                if index >= len(stock) and ours != ART_PAD:
                    raise SystemExit(f"art: {rel} line {index + 1} is {line!r} in the town's copy and "
                                     f"{merged[index]!r} in the art mod's: both claim that number")
                if index >= len(stock) and stock_count_is_fixed:
                    raise SystemExit(f"art: the town's {rel} has its own line {index + 1}; the art's FIDs start right "
                                     f"after the stock list, so nothing else can be appended to this file")
                merged[index] = line
    write_out(rel, "\r\n".join(merged) + "\r\n")
    return len(merged) - len(stock)


def merge_art_messages(rel, first_number):
    """Add the art protos' names and descriptions to the staged (or stock) message file.

    first_number is the first message number of the art's own protos (PID * 100): that range is
    the art's alone (registry.ART_FIRST_PID, lint_art). A staged file that holds OTHER texts there
    was written by this step from an older build of the art: a description has been reworded
    since. That is no collision; the file is then made afresh from the stock one. (It used to be
    reported as "... in the town's copy and ... in the art mod's", and every staging tree that was
    not wiped first, mod/megaton/out and the layout test's own among them, stopped building the
    day a piece's description changed.)"""
    from f2lib import msg as msgfile  # tools/f2lib

    with open(os.path.join(art_out(), rel), "rb") as f:
        art = msgfile.parse(f.read())
    stock_bytes = read_vanilla(rel).encode("latin-1")
    stock = msgfile.parse(stock_bytes)
    new = {number: entry for number, entry in art.items() if stock.get(number) != entry}
    staged = os.path.join(OUT, rel)
    base = stock_bytes
    if os.path.exists(staged):
        with open(staged, "rb") as f:
            base = f.read()
    have = msgfile.parse(base)
    stale = [number for number, entry in new.items()
             if number >= first_number and number in have and have[number] != entry and have[number] != stock.get(number)]
    town_own = [number for number, entry in have.items() if number < first_number and stock.get(number) != entry]
    if stale and not town_own:
        os.remove(staged)
        base = stock_bytes
        have = stock
    for number, entry in new.items():
        if number in have and have[number] != entry and have[number] != stock.get(number):
            raise SystemExit(f"art: {rel} entry {number} is {have[number][1]!r} in the town's copy and {entry[1]!r} in the art mod's")
    missing = {number: entry for number, entry in new.items() if have.get(number) != entry}
    if missing or not os.path.exists(staged):
        path = os.path.join(OUT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(msgfile.append_entries(base, missing) if missing else base)
    return len(new)


def step_art():
    """Stage the custom art: sprites and protos copied, lists and messages merged."""
    manifest = registry.art_manifest()
    source = art_out()
    if manifest is None or not os.path.isdir(source):
        raise SystemExit("art: mod/megaton-art has no manifest.json / out/: run python megaton.py setup first")
    sync_art_ledger()
    files = art_files(manifest)
    missing = [rel for rel in files if not os.path.exists(os.path.join(source, rel))]
    if missing:
        raise SystemExit(f"art: mod/megaton-art/out lacks {len(missing)} file(s) of the manifest, e.g. {missing[0]}: "
                         "run python megaton.py setup")
    for rel in files:
        target = os.path.join(OUT, rel)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        shutil.copyfile(os.path.join(source, rel), target)
    lines = texts = 0
    for kind, (folder, messages) in ART_KINDS.items():
        lines += merge_art_list(f"art/{folder}/{folder}.lst", True)
        lines += merge_art_list(f"proto/{folder}/{folder}.lst", False)
        texts += merge_art_messages(messages, registry.ART_FIRST_PID[kind] * 100)
    if "tiles" in manifest:
        lines += merge_art_list("art/tiles/tiles.lst", True)
    pieces = sum(1 for piece in manifest["pieces"].values() if piece.get("verdict") != "cut")
    print(f"art: {len(files)} sprite and proto files of {len(manifest['pieces'])} pieces ({pieces} in use) staged from "
          f"mod/megaton-art/out; {lines} list lines and {texts} message entries merged")


def lint_art():
    """The staged art the way the engine will look it up: PID -> proto list line -> file -> FID -> art list line -> FRM."""
    from f2lib import GameFiles, ids as f2ids  # tools/f2lib

    manifest = registry.art_manifest()
    if manifest is None:
        return True
    ok = True
    gf = GameFiles(overlay=OUT)
    stock = GameFiles()
    types = {"scenery": f2ids.OBJ_TYPE_SCENERY, "wall": f2ids.OBJ_TYPE_WALL}
    for kind, obj_type in types.items():
        if len(stock.art_list(obj_type)) != registry.ART_FIRST_ART[kind]:
            print(f"lint: ERR the stock {kind} art list has {len(stock.art_list(obj_type))} lines, registry.ART_FIRST_ART says {registry.ART_FIRST_ART[kind]}")
            ok = False
        if stock.protos.count(obj_type) >= registry.ART_FIRST_PID[kind]:
            print(f"lint: ERR stock {kind} protos reach PID {stock.protos.count(obj_type)}: registry.ART_FIRST_PID is taken")
            ok = False
    seen = {}
    for name, piece in manifest["pieces"].items():
        for part in piece["parts"]:
            pid, fid = int(part["pid"], 16), int(part["fid"], 16)
            kind = part["type"]
            if pid != f2ids.make_pid(types[kind], registry.ART_FIRST_PID[kind] + part["slot"]) \
                    or fid != f2ids.make_fid(types[kind], registry.ART_FIRST_ART[kind] + part["slot"]):
                print(f"lint: ERR art piece {name}: slot {part['slot']} does not give PID {part['pid']} / FID {part['fid']}")
                ok = False
                continue
            for key in (("pid", pid), ("fid", fid)):
                if seen.setdefault(key, name) != name:
                    print(f"lint: ERR art {key[0]} 0x{key[1]:08X} is used by {seen[key]} and {name}")
                    ok = False
            try:
                proto = gf.protos.get(pid)
                frm = gf.art.load(fid)
            except Exception as problem:            # noqa: BLE001 - whatever stops the engine is a finding
                print(f"lint: ERR art piece {name}: PID {part['pid']} / FID {part['fid']} cannot be loaded from the staged tree ({problem})")
                ok = False
                continue
            if proto.pid != pid or proto.fid != fid or frm.frame_count != part["frames"] \
                    or gf.protos.name(pid) != piece["title"]:
                print(f"lint: ERR art piece {name}: staged proto {part['pid']} is pid 0x{proto.pid:08X} fid 0x{proto.fid:08X}, "
                      f"{frm.frame_count} frame(s), named {gf.protos.name(pid)!r}")
                ok = False
    for define, pid in registry.art_pids(manifest).items():
        if not gf.protos.exists(pid):
            print(f"lint: ERR {define} 0x{pid:08X} has no staged proto")
            ok = False
    if "tiles" in manifest:
        # Validate the files in the town's staged tree, not only the art pipeline's output.
        sys.path.insert(0, registry.art_dir())
        from pipeline import tiles as art_tiles
        for problem in art_tiles.verify(manifest, out_dir=OUT):
            print(f"lint: ERR {problem}")
            ok = False
    return ok


def interface_art_ids():
    """{file name: index in the staged art/intrface/intrface.lst} for registry.INTERFACE_ART."""
    text = read_vanilla("art/intrface/intrface.lst")
    base = len(text.replace("\r\n", "\n").rstrip("\n").split("\n"))
    return {name: base + i for i, (name, _) in enumerate(registry.INTERFACE_ART)}


def step_data():
    # art/intrface: the world map's "MEGATON" plate, appended to the interface art list.
    import worldmap_art  # mod/megaton/worldmap_art.py
    from f2lib import GameFiles  # tools/f2lib

    art_ids = interface_art_ids()
    art_rows = [f"{name:<14} ; {comment}" for name, comment in registry.INTERFACE_ART]
    write_out("art/intrface/intrface.lst", append_lines(read_vanilla("art/intrface/intrface.lst"), art_rows))
    label = os.path.join(OUT, "art", "intrface", worldmap_art.LABEL_FILE)
    with open(label, "wb") as f:
        f.write(worldmap_art.build_label(GameFiles()))

    # maps.txt: append our maps after the last vanilla section.
    lines = []
    for index, lookup, stem, music, _ in registry.MAPS:
        lines += [
            "",
            f"[Map {index:03d}]",
            f"lookup_name={lookup}",
            f"map_name={stem}",
            f"music={music}",
            "ambient_sfx=gntlwin1:25, gntlwind:25, dogbark:20, dogbark1:20, gustwind:5, gustwin1:5",
            "saved=Yes",
            "dead_bodies_age=Yes",
            "can_rest_here=Yes,No,No",
            "automap=Yes",
        ]
    write_out("data/maps.txt", append_lines(read_vanilla("data/maps.txt"), lines))

    # city.txt: take over the cut-content area.
    city = read_vanilla("data/city.txt")
    start = city.index(f"[Area {registry.AREA:02d}]")
    end = city.index(f"[Area {registry.AREA + 1:02d}]")
    entrance_map = registry.MAPS[0][1]
    block = "\r\n".join([
        f"[Area {registry.AREA:02d}]                ; {registry.AREA_NAME} (Megaton mod; vanilla: unused)",
        f"area_name={registry.AREA_NAME}",
        f"world_pos={registry.AREA_WORLD_POS[0]},{registry.AREA_WORLD_POS[1]}",
        "start_state=On",
        f"size={registry.AREA_SIZE}",
        "townmap_art_idx=-1",
        f"townmap_label_art_idx={art_ids[worldmap_art.LABEL_FILE]}",
        f"entrance_0=On,-1,-1,{entrance_map},-1,-1,0",
        "",
        "",
    ])
    write_out("data/city.txt", city[:start] + block + city[end:])

    # map.msg: town name (area caption, Pip-Boy heading) and automap level names.
    msg = read_vanilla("text/english/game/map.msg")
    out_lines = []
    replaced = False
    for line in msg.split("\r\n"):
        if line.startswith(f"{{{registry.MAP_MSG_AREA_NAME_ID}}}"):
            line = f"{{{registry.MAP_MSG_AREA_NAME_ID}}}{{}}{{{registry.AREA_NAME}}}"
            replaced = True
        out_lines.append(line)
    if not replaced:
        raise SystemExit(f"map.msg has no entry {registry.MAP_MSG_AREA_NAME_ID}")
    extra = []
    for index, _, _, _, level_names in registry.MAPS:
        for elevation, name in enumerate(level_names):
            extra.append(f"{{{200 + 3 * index + elevation}}}{{}}{{{name}}}")
    write_out("text/english/game/map.msg", append_lines("\r\n".join(out_lines), extra))

    # quests.txt / quests.msg
    quest_rows = ["#####", "# Megaton", "#####"]
    quest_text = []
    for msg_id, text, gvar, shown, done in registry.QUESTS:
        quest_rows.append(f"{registry.MAP_MSG_AREA_NAME_ID}, {msg_id}, {registry.GVARS[gvar]}, {shown}, {done}")
        quest_text.append(f"{{{msg_id}}}{{}}{{{text}}}")
    write_out("data/quests.txt", append_lines(read_vanilla("data/quests.txt"), quest_rows))
    write_out("text/english/game/quests.msg", append_lines(read_vanilla("text/english/game/quests.msg"), quest_text))

    # scripts.lst / scrname.msg: our scripts go after the vanilla ones.
    ids = script_ids()
    lst_rows = []
    name_rows = []
    for stem, display, comment in registry.SCRIPTS:
        index, _ = ids[stem]
        lst_rows.append(f"{stem + '.int':<15} ; {comment:<45} # local_vars={registry.LOCAL_VARS}")
        name_rows.append(f"{{{101 + index}}}{{}}{{{display}}}")
    write_out("scripts/scripts.lst", append_lines(read_vanilla("scripts/scripts.lst"), lst_rows).rstrip("\r\n"))
    write_out("text/english/game/scrname.msg", append_lines(read_vanilla("text/english/game/scrname.msg"), name_rows))

    print(f"data: staged tables for {len(registry.MAPS)} map(s), {len(registry.SCRIPTS)} script(s), {len(registry.QUESTS)} quest(s)")


def stage_module():
    """The module given with --stage (loaded once), or None."""
    global _STAGE_MODULE
    if STAGE and _STAGE_MODULE is None:
        import importlib.util

        spec = importlib.util.spec_from_file_location("megaton_stage", STAGE)
        _STAGE_MODULE = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(_STAGE_MODULE)
    return _STAGE_MODULE


def stage_script_setup():
    """(directories searched for script sources, -D defines) for the scripts step."""
    dirs = [SCRIPTS_SRC]
    defines = []
    stage = stage_module()
    if stage is not None:
        stand_ins = getattr(stage, "SCRIPTS_DIR", None)
        if stand_ins:
            stand_ins = os.path.join(os.path.dirname(STAGE), stand_ins)
            if not os.path.isdir(stand_ins):
                raise SystemExit(f"scripts: the stage's SCRIPTS_DIR {stand_ins} does not exist")
            dirs.insert(0, stand_ins)
        for name, (hx, hy, rotation) in (getattr(stage, "SPOTS", None) or {}).items():
            defines += ["-D", f"TILE_{name}=({hy * 200 + hx})", "-D", f"ROT_{name}=({rotation})"]
    return dirs, defines


def step_scripts():
    compiler = os.path.join(ROOT, "tools", "ssl.py")
    headers = os.path.join(ROOT, "mod", "scripts_src", "headers")
    source_dirs, defines = stage_script_setup()
    runtime = os.path.join(ROOT, "tools", "sslc", "build", "bin")
    runtimes = [os.path.isfile(os.path.join(runtime, name)) for name in ("sslc.mjs", "sslc.wasm")]
    import prebuilt
    if any(runtimes) and not all(runtimes):
        raise SystemExit("scripts: compiler installation is incomplete; repair it before building")
    if not (all(runtimes) and shutil.which("node")):
        try:
            count = prebuilt.copy_verified(ROOT, os.path.join(OUT, "scripts"),
                stage=STAGE, defines=defines, source_dirs=source_dirs, only=ONLY)
        except prebuilt.PrebuiltError as error:
            raise SystemExit("scripts: " + str(error)) from None
        for stem, _, _ in registry.SCRIPTS:
            dialog = os.path.join(SCRIPTS_SRC, stem + ".msg")
            if os.path.isfile(dialog):
                destination = os.path.join(OUT, "text", "english", "dialog", stem + ".msg")
                os.makedirs(os.path.dirname(destination), exist_ok=True)
                shutil.copyfile(dialog, destination)
        print(f"scripts: used {count} verified prebuilt scripts")
        return
    try:
        prebuilt.compiler_identity(ROOT)
    except prebuilt.PrebuiltError as error:
        raise SystemExit("scripts: " + str(error)) from None
    count = 0
    missing = []
    stand_ins = []
    for stem, _, _ in registry.SCRIPTS:
        if ONLY and stem not in ONLY:
            continue
        source = next((os.path.join(d, stem + ".ssl") for d in source_dirs if os.path.exists(os.path.join(d, stem + ".ssl"))), None)
        if source is None:
            # The slot stays reserved in scripts.lst; nothing may reference it yet.
            missing.append(stem)
            continue
        if os.path.dirname(source) != SCRIPTS_SRC:
            stand_ins.append(stem)
        target = os.path.join(OUT, "scripts", stem + ".int")
        os.makedirs(os.path.dirname(target), exist_ok=True)
        result = subprocess.run([sys.executable, compiler, "compile", source, "-o", target, "-I", headers, "-I", SCRIPTS_SRC] + defines)
        if result.returncode != 0 or not os.path.exists(target) or os.path.getsize(target) == 0:
            raise SystemExit(f"scripts: {stem}.ssl failed to compile")
        dialog = source[:-4] + ".msg"
        dest = os.path.join(OUT, "text", "english", "dialog", stem + ".msg")
        if os.path.exists(dialog):
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            shutil.copyfile(dialog, dest)
        elif os.path.exists(dest):
            os.remove(dest)
        count += 1
    print(f"scripts: compiled {count}"
          + (f" ({len(defines) // 4} spots moved by the stage)" if defines else "")
          + (f"; stand-ins from the stage: {' '.join(stand_ins)}" if stand_ins else "")
          + (f"; not written yet: {' '.join(missing)}" if missing else ""))


def step_protos():
    if not os.path.exists(os.path.join(HERE, "protos.py")):
        print("protos: protos.py not written yet, skipped")
        return
    import protos  # mod/megaton/protos.py

    protos.build_protos(OUT)


def step_maps():
    if STAGE:
        stage_module().build_maps(OUT)
        print(f"maps: test stage {os.path.relpath(STAGE, ROOT)}")
        return
    from layout import build_maps  # mod/megaton/layout/__init__.py

    # The real town is strict unless --only left scripts out on purpose: a cast entry whose
    # script is not compiled, or whose door / bed / container the layout did not provide, is
    # a build error instead of a silently unscripted object.
    build_maps(OUT, strict=not ONLY)


def config_read(path):
    """INI reader with the engine's quirks (configParseLine)."""
    cfg = {}
    last = "unknown"
    with open(path, "rb") as f:
        raw_lines = f.read().split(b"\n")
    for raw in raw_lines:
        s = raw.decode("latin-1")
        if len(s) > 255:
            print("lint: WARN line longer than the engine's 256-char buffer:", s[:40])
        i = s.find(";")
        if i >= 0:
            s = s[:i]
        s = s.lstrip()
        if s.startswith("["):
            j = s.find("]", 1)
            if j >= 0:
                last = s[1:j].strip()
                continue
        if "=" not in s:
            continue
        key, value = s.split("=", 1)
        cfg.setdefault(last.lower(), {})[key.strip().lower()] = value.strip()
    return cfg


def token(s):
    s = s.lstrip(" ")
    i = s.find(",")
    return (s, "") if i < 0 else (s[:i], s[i + 1:])


def step_lint():
    """Emulates wmMapInit / wmAreaInit: a typo in these tables stops the game at startup."""
    ok = True
    maps_cfg = config_read(os.path.join(OUT, "data", "maps.txt"))
    maps = []
    while True:
        section = maps_cfg.get("map %03d" % len(maps))
        if not section or "lookup_name" not in section:
            break
        index = len(maps)
        if "map_name" not in section:
            print(f"lint: FATAL Map {index:03d} has no map_name")
            ok = False
        if len(section["lookup_name"]) > 39 or len(section.get("map_name", "")) > 8:
            print(f"lint: ERR Map {index:03d} name too long")
            ok = False
        for key in ("saved", "dead_bodies_age", "pipboy_active", "automap"):
            if key in section and token(section[key])[0].lower() not in ("yes", "no"):
                print(f"lint: FATAL Map {index:03d} {key}={section[key]!r} is not yes/no")
                ok = False
        maps.append(section)
    if len(maps) > AUTOMAP_MAP_COUNT:
        print(f"lint: ERR more than {AUTOMAP_MAP_COUNT} maps (automap tables overflow)")
        ok = False
    for index, lookup, stem, _, _ in registry.MAPS:
        if index >= len(maps) or maps[index]["lookup_name"] != lookup or maps[index].get("map_name") != stem:
            print(f"lint: ERR Map {index:03d} is not {lookup}/{stem} after parsing (gap or wrong order?)")
            ok = False

    lookup = {}
    for index, section in enumerate(maps):
        lookup.setdefault(section["lookup_name"].lower(), index)

    city_cfg = config_read(os.path.join(OUT, "data", "city.txt"))
    areas = 0
    while areas < 5000:
        section = city_cfg.get("area %02d" % areas)
        if not section or "townmap_art_idx" not in section:
            break
        for required in ("area_name", "world_pos", "start_state", "size"):
            if required not in section:
                print(f"lint: FATAL Area {areas:02d} is missing {required}")
                ok = False
        if token(section.get("start_state", ""))[0].lower() not in ("on", "off"):
            print(f"lint: FATAL Area {areas:02d} start_state")
            ok = False
        if token(section.get("size", ""))[0].lower() not in ("small", "medium", "large"):
            print(f"lint: FATAL Area {areas:02d} size")
            ok = False
        entrance = 0
        while entrance < 10 and f"entrance_{entrance}" in section:
            rest = section[f"entrance_{entrance}"]
            state, rest = token(rest)
            _, rest = token(rest)
            _, rest = token(rest)
            name, rest = token(rest)
            if state.lower() not in ("on", "off"):
                print(f"lint: FATAL Area {areas:02d} entrance_{entrance} state {state!r}")
                ok = False
            if name.lower() not in lookup:
                print(f"lint: FATAL Area {areas:02d} entrance_{entrance}: map {name!r} is not in maps.txt (game will not start)")
                ok = False
            entrance += 1
        if entrance == 0:
            print(f"lint: ERR Area {areas:02d} has no entrance_0")
            ok = False
        areas += 1
    if areas != CITY_COUNT:
        print(f"lint: FATAL {areas} areas, the engine requires exactly {CITY_COUNT}")
        ok = False

    # intrface.lst: the label the staged city.txt points at must be our plate, and the file must be there.
    art_lst = open(os.path.join(OUT, "art", "intrface", "intrface.lst"), "rb").read().decode("latin-1").replace("\r\n", "\n").rstrip("\n").split("\n")
    megaton_area = city_cfg.get("area %02d" % registry.AREA, {})
    for name, index in interface_art_ids().items():
        if index >= len(art_lst) or not art_lst[index].lower().startswith(name) or not os.path.exists(os.path.join(OUT, "art", "intrface", name)):
            print(f"lint: ERR art/intrface/intrface.lst line {index} is not {name}, or the file is missing")
            ok = False
    label_index = megaton_area.get("townmap_label_art_idx", "-1")
    if not label_index.isdigit() or int(label_index) >= len(art_lst):
        print(f"lint: ERR Area {registry.AREA:02d} townmap_label_art_idx={label_index} is not a line of intrface.lst")
        ok = False

    # scripts.lst: every registered script must sit on the line its id says.
    lst = open(os.path.join(OUT, "scripts", "scripts.lst"), "rb").read().decode("latin-1").replace("\r\n", "\n").rstrip("\n").split("\n")
    for stem, (index, _) in script_ids().items():
        if index >= len(lst) or not lst[index].lower().startswith(stem + ".int"):
            print(f"lint: ERR scripts.lst line {index} is not {stem}.int")
            ok = False

    # Message files: a stray brace silently swallows every later line of the file.
    from f2lib import msg as msgfile  # tools/f2lib

    dialog_dir = os.path.join(OUT, "text", "english", "dialog")
    dialogs = sorted(os.listdir(dialog_dir)) if os.path.isdir(dialog_dir) else []
    for name in dialogs:
        try:
            with open(os.path.join(dialog_dir, name), "rb") as f:
                msgfile.parse(f.read())
        except ValueError as problem:
            print(f"lint: ERR text/english/dialog/{name}: {problem}")
            ok = False

    # Spots: scripts get them as tile numbers, the engine can only centre on part of the grid.
    from layout import spots

    for name, (hx, hy, rotation) in spots.SPOTS.items():
        if not (0 <= hx < 200 and 0 <= hy < 200 and 0 <= rotation < 6):
            print(f"lint: ERR spot {name} = ({hx}, {hy}, {rotation}) is not on the hex grid")
            ok = False

    gvars = list(registry.GVARS.values())
    if len(set(gvars)) != len(gvars) or any(not 634 <= g <= 692 for g in gvars):
        print("lint: ERR GVARs must be unique and inside the reserved block 634..692")
        ok = False

    flags = list(registry.FLAGS.values())
    if len(set(flags)) != len(flags) or any(f <= 0 or f & (f - 1) or f >= 1 << 31 for f in flags):
        print("lint: ERR MG_F_* flags must be distinct single bits below 1 << 31")
        ok = False
    stems = [stem for stem, _, _ in registry.SCRIPTS]
    if len(set(stems)) != len(stems) or any(len(stem) > 8 or not stem.startswith("mg") and stem != "megaton" for stem in stems):
        print("lint: ERR script stems must be unique, at most 8 characters and start with mg")
        ok = False

    art_staged = os.path.exists(os.path.join(OUT, "proto", "scenery", "scenery.lst"))
    if art_staged and not lint_art():
        ok = False

    print(f"lint: {len(maps)} maps, {areas} areas, {len(lst)} scripts, {len(dialogs)} dialogue files"
          + (", custom art" if art_staged else "") + f" -> {'OK' if ok else 'BROKEN'}")
    if not ok:
        raise SystemExit(1)


def staged_files():
    """{game path (lower-case, forward slashes): absolute file} for everything staged."""
    files = {}
    for base, _, names in os.walk(OUT):
        for name in names:
            full = os.path.join(base, name)
            rel = os.path.relpath(full, OUT).replace(os.sep, "/")
            if rel.endswith(".dat") or name.startswith("."):
                continue
            files[rel.lower()] = full
    return files


def step_pack():
    from f2lib import dat2  # tools/f2lib

    files = {rel: open(full, "rb").read() for rel, full in sorted(staged_files().items())}
    target = os.path.join(OUT, "patch001.dat")
    dat2.write_dat2(files, target)
    print(f"pack: {os.path.relpath(target, ROOT)} ({len(files)} files, {os.path.getsize(target)} bytes)")


def step_web():
    print("Browser hosting is not included in this repository. Use python megaton.py install for a native game.", file=sys.stderr)
    raise SystemExit(2)


STEPS = {
    "ids": step_ids,
    "data": step_data,
    "protos": step_protos,
    "art": step_art,
    "scripts": step_scripts,
    "maps": step_maps,
    "lint": step_lint,
    "pack": step_pack,
    "web": step_web,
}


STAGE = None
ONLY = None
_STAGE_MODULE = None


def main(argv):
    global OUT, STAGE, ONLY
    args = argv[1:]
    while args and args[0] in ("--out", "--stage", "--only"):
        if len(args) < 2:
            print(__doc__)
            return 2
        if args[0] == "--out":
            OUT = os.path.abspath(args[1])
        elif args[0] == "--stage":
            STAGE = os.path.abspath(args[1])
        else:
            ONLY = set(args[1].split(","))
        args = args[2:]
    steps = args or [name for name in STEPS if name != "web"]
    for name in steps:
        if name not in STEPS:
            print(__doc__)
            return 2
    for name in steps:
        STEPS[name]()
    if not args and OUT == os.path.join(HERE, "out"):
        print("Built out/patch001.dat. Install with python megaton.py install.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
