# SPDX-License-Identifier: MIT
"""Tile sheet demos: one of every kind, used by the tile proof (stage/tiles) and as patterns to copy.

    python3 mod/megaton-art/build.py tiles preview sheets/demo_tiles.py [NAME]
    python3 mod/megaton-art/build.py tiles add sheets/demo_tiles.py

    mgx_roof_demo    a whole roof for a 7 x 7-square shack: mismatched tin, a plank patch, a tarp held
                     down by tyres, a hole with rafters, a hatch with a red lamp that glows at night
    mgx_tin_wrap     3 x 2 squares of tin that repeat without a seam: roof by the square metre
    mgx_plates       2 x 2 squares of solid steel floor plates (a floor sheet has no holes)
    mgx_junk         3 x 2 squares of DECAL: boards, a tyre, scrap lying on whatever ground is there
Do not edit this file for your own sheets: copy the pattern into sheets/<yours>.py.
"""
from kit import sheet, geo, mat, T
from kit import sheet_kit as sk

BOX = (100, 101, 114, 111)              # any stock shack of 7 x 7 roof squares
S = T.Shack(BOX)


@sheet("mgx_roof_demo", kind="roof", size=S.size, title="Patched Roof")
def mgx_roof_demo(ctx):
    r = ctx.rng
    back, front = S.stock_back - 0.25, S.stock_front + 0.35        # a little more overhang than stock, both ways
    hole = (3.9, 4.2, 5.6, 6.5)                                    # x0, y0, x1, y1 of the hole
    deck = (6.3, 2.2, 8.6, 5.2)                                    # plank patch
    cover = (1.0, 6.4, 3.4, 8.9)                                   # tarp

    def skip(xa, ya, xb, yb):
        def inside(box, grow=0.0):
            return xa > box[0] - grow and xb < box[2] + grow and ya > box[1] - grow and yb < box[3] + grow
        return inside(hole, 0.75) or inside(deck, 0.2)

    sk.tin_field(0.0, back, ctx.w, front, seed=11, rust=(0.12, 0.7), skip=skip,
                 paints=((0.10, 0.20, 0.24), (0.34, 0.07, 0.05), (0.33, 0.30, 0.16)), paint_share=0.2)
    # the hole: rafters and battens under it, one sheet hanging into it
    sk.rafters(hole[0] - 0.9, hole[1] - 0.5, hole[2] + 0.9, hole[3] + 0.5, z=-0.05, spacing=0.55)
    sk.tin(hole[0] - 0.3, hole[1] + 0.9, hole[0] + 0.5, hole[3] + 0.2, z=-0.02, slope=6.0, roll=-9.0, rust=0.95, seed=41)
    # the patch of boards, nailed over a rotten corner, two boards missing
    sk.plank_deck(deck[0], deck[1], deck[2], deck[3], z=0.05, along="y", board=0.22, ragged=0.35, missing=0.12, seed=5)
    sk.rafters(deck[0], deck[1], deck[2], deck[3], z=0.0, spacing=0.7, purlins=False)
    # a tarp over the front corner, tyres and a block on it
    sk.tarp(cover[0], cover[1], cover[2], cover[3], z=0.07, colour=(0.10, 0.17, 0.20), sag=0.05, seed=3)
    sk.weights([(1.3, 6.7), (3.1, 6.8), (1.4, 8.6), (3.0, 8.5)], kind="mix", seed=8, z=0.1)
    # a hatch with a lamp: the lamp's glass is painted with an animated palette range (not dimmed at night)
    sk.plate(8.2, 6.6, 9.1, 7.6, z=0.05, thickness=0.06, material=mat.painted_metal((0.30, 0.26, 0.08), flaking=0.5, seed=2))
    geo.cylinder(0.05, 0.22, (8.95, 6.75, 0.11), mat.steel(rust=0.4))
    geo.set_fx(geo.bulb((8.95, 6.75, 0.40), colour=(1.0, 0.2, 0.1), radius=0.07, strength=3.0), "fire")
    # loose things that make a roof look lived on
    sk.weights([(0.7, 2.0), (5.9, 1.6), (9.0, 3.4), (7.4, 9.6), (4.4, 9.4)], kind="mix", seed=21, z=0.06)
    geo.pipe([(0.5, 4.6, 0.12), (3.4, 4.9, 0.12), (3.5, 6.0, 0.12)], 0.05, mat.steel(rust=0.8, seed=4))
    for k in range(3):
        sk.plate(2.2 + 2.6 * k + r.uniform(-0.3, 0.3), 9.3, 2.9 + 2.6 * k, 10.1, z=0.05, thickness=0.015,
                 rot=r.uniform(-12, 12), material=mat.steel(rust=r.uniform(0.5, 0.95), seed=k))


@sheet("mgx_tin_wrap", kind="roof", size=(3, 2), wrap=True, title="Tin Roofing")
def mgx_tin_wrap(ctx):
    sk.tin_field(-0.2, -0.2, ctx.w + 0.2, ctx.h + 0.2, seed=4, sheet=(0.92, 1.6), jitter=0.12, rust=(0.15, 0.55))


@sheet("mgx_plates", kind="floor", size=(2, 2), title="Floor Plates")
def mgx_plates(ctx):
    sk.plate(-1.0, -1.0, ctx.w + 1.0, ctx.h + 1.0, z=-0.05, thickness=0.05, material=mat.concrete(colour=(0.10, 0.095, 0.09)))
    for i in range(2):
        for j in range(2):
            x, y = ctx.square(i, j)
            sk.plate(x + 0.05, y + 0.05, x + T.SQ_U - 0.05, y + T.SQ_V - 0.05, z=0.0, thickness=0.02,
                     material=mat.steel(rust=0.35 + 0.2 * ((i + j) % 2), colour=(0.30, 0.30, 0.31), seed=i * 3 + j))


@sheet("mgx_junk", kind="floor", size=(3, 2), decal=True, title="Scrap On The Ground")
def mgx_junk(ctx):
    sk.plank_deck(0.5, 0.4, 1.9, 2.6, z=0.0, along="y", board=0.2, ragged=0.5, missing=0.25, seed=9, grey=0.6)
    geo.tire((2.9, 1.0, 0.0), lying=True, seed=2)
    sk.plate(2.3, 2.0, 3.3, 2.7, z=0.0, thickness=0.02, rot=18.0, material=mat.corrugated(rust=0.9, seed=6))
    sk.plate(3.4, 0.5, 3.9, 0.9, z=0.0, thickness=0.015, rot=-30.0, material=mat.painted_metal((0.3, 0.07, 0.05), seed=3))
    geo.pipe([(0.3, 2.9, 0.05), (2.0, 3.0, 0.05), (3.6, 2.6, 0.05)], 0.05, mat.steel(rust=0.9, seed=1))
