#!/usr/bin/env python3
# SPDX-License-Identifier: LicenseRef-Sustainable-Use
"""Generate SSL headers with PID_* and GVAR_* constants from extracted game data.

    gen_pid_header.py [--data GAME_TREE] [--out mod/scripts_src/headers]

Writes two files into --out:

  pids.h   one #define per item, critter and scenery prototype, named after the
           prototype's display name in text/english/game/pro_*.msg:
               items    PID_<NAME>        value = prototype number
               critters PID_CR_<NAME>     value = 0x01000000 | number
               scenery  PID_SC_<NAME>     value = 0x02000000 | number
           A name shared by several prototypes of one kind gets the prototype
           number appended to every one of them (PID_KEY_82, PID_KEY_105), so a
           define never silently means "one of the lockers".
  gvars.h  the global variable names and indexes of data/vault13.gam.

The prototype number is the 1-based line of proto/<kind>/<kind>.lst; the name is
looked up through the message id stored in the .pro file (offset 4).
"""
import argparse
import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (proto dir, message file, define prefix, PID type)
KINDS = (
    ("items", "pro_item.msg", "PID_", 0),
    ("critters", "pro_crit.msg", "PID_CR_", 1),
    ("scenery", "pro_scen.msg", "PID_SC_", 2),
)

MSG_ENTRY = re.compile(r"\{(\d+)\}\{[^}]*\}\{([^}]*)\}")


def find(base, *parts):
    """Joins path components case-insensitively (extractions differ in case)."""
    path = base
    for part in parts:
        match = [n for n in os.listdir(path) if n.lower() == part.lower()]
        if not match:
            raise FileNotFoundError(os.path.join(path, part))
        path = os.path.join(path, match[0])
    return path


def read_msg(path):
    with open(path, "rb") as f:
        text = f.read().decode("cp1252", "replace")
    return {int(number): value for number, value in MSG_ENTRY.findall(text)}


def identifier(name):
    return re.sub(r"[^A-Z0-9]+", "_", name.upper().replace("'", "")).strip("_")


def proto_names(data_dir, kind, msg_file):
    """Yields (prototype number, display name) for every prototype that has a name."""
    messages = read_msg(find(data_dir, "text", "english", "game", msg_file))
    proto_dir = find(data_dir, "proto", kind)
    with open(find(proto_dir, kind + ".lst"), "rb") as f:
        files = f.read().decode("latin-1").split()
    for number, file_name in enumerate(files, start=1):
        try:
            with open(find(proto_dir, file_name), "rb") as f:
                (message_id,) = struct.unpack(">i", f.read(8)[4:8])
        except (FileNotFoundError, struct.error):
            continue
        name = messages.get(message_id, "").strip()
        if identifier(name):
            yield number, name


def pid_lines(data_dir):
    lines = []
    for kind, msg_file, prefix, pid_type in KINDS:
        entries = [(number, name, identifier(name)) for number, name in proto_names(data_dir, kind, msg_file)]
        counts = {}
        for _, _, ident in entries:
            counts[ident] = counts.get(ident, 0) + 1
        lines.append("")
        lines.append("/* %s: %d prototypes */" % (kind, len(entries)))
        for number, name, ident in entries:
            define = prefix + ident + ("_%d" % number if counts[ident] > 1 else "")
            value = "(%d)" % number if pid_type == 0 else "(0x%08X)" % ((pid_type << 24) | number)
            lines.append("#define %-44s %-14s // %s" % (define, value, name))
    return lines


def gvar_lines(data_dir):
    """vault13.gam as the engine reads it (globalVarsRead, src/game.cc): after the section
    line every line that is not empty and does not start with // is the next variable."""
    with open(find(data_dir, "data", "vault13.gam"), "rb") as f:
        text = f.read().decode("latin-1")
    lines = []
    index = None
    for line in text.splitlines():
        if index is None:
            if line.startswith("GAME_GLOBAL_VARS:"):
                index = 0
            continue
        if not line or line.startswith("//"):
            continue
        name = re.match(r"\s*(\w+)", line)
        value = re.search(r"=\s*(-?\d+)", line)
        if name:
            lines.append("#define %-44s (%d)%s" % (name.group(1), index,
                         "   // initial value %s" % value.group(1) if value and value.group(1) != "0" else ""))
        index += 1
    return lines


def write_header(path, guard, title, lines):
    body = ["/* %s" % title, " * Generated by tools/gen_pid_header.py from the extracted game data. Do not edit. */",
            "#ifndef %s" % guard, "#define %s" % guard] + lines + ["", "#endif", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body))
    return len([line for line in lines if line.startswith("#define")])


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", help="extracted game tree; otherwise use the selected game")
    ap.add_argument("--out", default=os.path.join(ROOT, "mod", "scripts_src", "headers"), help="output directory")
    args = ap.parse_args()

    if args.data is None:
        from f2lib.gamepath import resolve_game
        args.data = str(resolve_game())
    os.makedirs(args.out, exist_ok=True)
    try:
        pids = write_header(os.path.join(args.out, "pids.h"), "FO2_PIDS_H", "Prototype ids (PID_*).", pid_lines(args.data))
        gvars = write_header(os.path.join(args.out, "gvars.h"), "FO2_GVARS_H",
                             "Global variable indexes (data/vault13.gam).", [""] + gvar_lines(args.data))
    except FileNotFoundError as error:
        print("missing game data file: %s" % error, file=sys.stderr)
        return 1
    print("%s: %d defines" % (os.path.join(args.out, "pids.h"), pids))
    print("%s: %d defines" % (os.path.join(args.out, "gvars.h"), gvars))
    return 0


if __name__ == "__main__":
    sys.exit(main())
